name: Daily data fetching

on:
  schedule:
    - cron:  '0 17 * * *'

jobs:
    build:

        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v2
            
          - name: Installing dependencies
            run: npm install
          
          - name: Updating the data
            run: node src/index.js

          - name: Commit and push last data
            run: |
              git config --global user.name 'dej611'
              git config --global user.email 'dej611@users.noreply.github.com'
              git add .
              git commit -m':sparkles: Dataset updated'
              git push

